name: CI/CD Pipeline for Java Spring Boot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Isso será substituído por 'arthurwrx'
          password: ${{ secrets.DOCKER_TOKEN }}      # Isso será substituído pelo seu token

      - name: Build and push Docker image for staging
        run: |
          docker build -t your-dockerhub-username/java_project:staging .
          docker push your-dockerhub-username/java_project:staging

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging environment"
          # Aqui você colocaria seu script de deployment (Ex: Docker Compose, Kubernetes)
          # Exemplo para Docker Compose:
          # docker-compose -f docker-compose.staging.yml up -d

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'  # Apenas quando for um push na branch 'master'
        run: |
          echo "Deploying to Production environment"
          # Exemplo para Production:
          # docker-compose -f docker-compose.production.yml up -d
