name: CI/CD Pipeline for Java Spring Boot

## 1 Passo - Gatilhos funcionam a partir da branch master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

## 02 - Inicia os jobs para construção da imagem

jobs:
  build: 
    ## 2.1 - Cria a imagem do ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
    ## 2.2 - Configura o Java 17
      - name: Configura o Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image for staging
        run: |
          docker build -t arthurwrx/java-project:staging .
          docker push arthurwrx/java-project:staging

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging environment"
          docker compose -f docker-compose.staging.yml up -d

      - name: Deploy to Production

        run: |
          echo "Deploying to Production environment"
          docker compose -f docker-compose.production.yml up -d
